apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: 'first'
  name: dotnetdeploy
  namespace: ataproj
  labels:
    app: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: registry.ataair.ir/ataapp/argoocelot/dotnet:v1
        ports:
        - containerPort: 8080
        #readinessProbe:
         # exec:
          #  command:
           #   - "ls"
            #  - "/etc/nginx/conf.d"
         # initialDelaySeconds: 10
         # periodSeconds: 15
         # successThreshold: 1
         # failureThreshold: 2
         #  livenessProbe:
         # httpGet:
         #   path: /
         #   port: 8080
         #   httpHeaders:
         # initialDelaySeconds: 3
         # periodSeconds: 3
      imagePullSecrets:
      - name: atareg2
