apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocelot
  namespace: ataproj
  labels:
    name: ocelot
spec:
  ingressClassName: nginx
  rules:
  - host: sample.ataair.ir
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ocelotsvc
            port:
              number: 80
