apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redispvc
  namespace: ataproj
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
